[tools]
bun = 'latest'

[tasks.bun-install]
description = "Install dependencies using pnpm"
run = "bun install"
sources = ['package.json', 'bun.', 'mise.toml']

[tasks.dev]
description = "Calls your dev script in `package.json`"
run = ["bun run dev"]
depends = ["bun-install"]
