/** @type {import('prettier').Config & import('prettier-plugin-tailwindcss').options} */
const config = {
	endOfLine: "lf",
	semi: false,
	singleQuote: false,
	tabWidth: 2,
	useTabs: true,
	trailingComma: "es5",
	importOrder: [
		"^(react/(.*)$)|^(react$)",
		"^(next/(.*)$)|^(next$)",
		"<THIRD_PARTY_MODULES>",
		"",
		"^types$",
		"^@/types/(.*)$",
		"^@/config/(.*)$",
		"^@/lib/(.*)$",
		"^@/hooks/(.*)$",
		"",
		"^@/components/ui/(.*)$",
		"^@/components/(.*)$",
		"",
		"^@/registry/(.*)$",
		"^@/styles/(.*)$",
		"^@/app/(.*)$",
		"",
		"",
		"^@/assets/(.*)$",
		"",
		"^[./]",
	],
	importOrderSeparation: false,
	importOrderSortSpecifiers: true,
	importOrderBuiltinModulesToTop: true,
	importOrderMergeDuplicateImports: true,
	importOrderCombineTypeAndValueImports: true,
	importOrderParserPlugins: ["typescript", "jsx"],
	plugins: [
		"@ianvs/prettier-plugin-sort-imports",
		"prettier-plugin-tailwindcss",
	],
	tailwindConfig: "./tailwind.config.js",
	tailwindFunctions: [
		"clsx",
		"tw",
		"apply",
		"theme",
		"variants",
		"e",
		"screen",
		"cn",
	],
}

export default config
